import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Astro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Astro - Live on AWS Amplify!
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://pcarlton.co"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by desperation
        </a>
      </footer>
    </div>
  )
}
